CC=g++
CFLAGS+=-Wall -O0 -std=c++0x -g
LFLAGS=-pthread

%.o : %.cxx
	$(CC) $(CFLAGS) -c -o $@ $<

asio/asio/include/asio.hpp:
	@if [ ! -d "asio" ]; then git clone https://github.com/andy-yx-chen/asio.git ; fi;

test:	asio/asio/include/asio.hpp
	@cd tests && make -f Makefile.lx testr && ./debug/testr
