CC=c++
CFLAGS=-std=c++0x -O0 -Wall -Iasio/asio/include -g -DOS_FREEBSD
LFLAGS=-lpthread
.PATH.o		: debug/

.SUFFIXES	: .o .cxx
.cxx.o	:
	$(CC) $(CFLAGS) -c $(.IMPSRC)

asio/asio/include/asio.hpp:
	@if [ ! -d "asio" ]; then git clone https://github.com/andy-yx-chen/asio.git ; fi;

test:	asio/asio/include/asio.hpp
	@cd tests && make -f Makefile.bsd testr && ./debug/testr
