CC=g++
CFLAGS+=-Wall -O0 -std=c++0x -g -D_GLIBCXX_USE_NANOSLEEP
LFLAGS=-pthread 
VPATH=../:./

%.o : %.cxx
	$(CC) $(CFLAGS) -c -o $@ $<

OBJS=test_async_result.o test_strfmt.o test_runner.o buffer.o snapshot.o snapshot_sync_req.o srv_config.o cluster_config.o test_buffer.o test_serialization.o

testr: $(OBJS)
	$(CC) -o $@ $^ -Wl,--no-as-needed $(LFLAGS)
	@-rm -rf debug
	@-mkdir debug
	@-mv *.o debug/
	@-mv $@ debug/

clean:
	@-rm -rf debug
