CC=g++
CFLAGS+=-Wall -O0 -std=c++0x -g -D_GLIBCXX_USE_NANOSLEEP
LFLAGS=-pthread 

%.o : %.cxx
	$(CC) $(CFLAGS) -c -o $@ $<

OBJS=test_async_result.o test_strfmt.o test_runner.o

testr: $(OBJS)
	$(CC) -o $@ $^ -Wl,--no-as-needed $(LFLAGS)
	@-mkdir debug
	@-mv *.o debug/
	@-mv $@ debug/

clean:
	@-rm -rf debug
