CC=c++
CFLAGS+=-std=c++0x -O0 -Wall
LFLAGS=-lpthread
.PATH.cxx	: ../
.PATH.o		: debug/
OBJS=test_async_result.o test_strfmt.o test_runner.o buffer.o snapshot.o snapshot_sync_req.o srv_config.o cluster_config.o test_buffer.o test_serialization.o

.SUFFIXES	: .o .cxx
.cxx.o	:
	$(CC) $(CFLAGS) -c $(.IMPSRC)
testr	: $(OBJS)
	$(CC) $(LFLAGS) -o $(.TARGET) $(.ALLSRC)
	@-rm -rf debug
	@-mkdir debug
	@-mv *.o debug/
	@-mv $(.TARGET) debug/

clean	:
	@-rm -rf debug

